version: '3'
services:
  lego-mongo:
    image: mongo
    container_name: lego-mongo
    volumes:
      - '.docker-volumns/mongo/data:/data/db'
      - '$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/' # 映射运行脚本文件夹
    ports:
      - 27017:27017
    env_file:
      - .env
  lego-redis:
    image: redis
    container_name: lego-redis
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    env_file: 
      - .env
  lego-backend:
    image: registry.cn-shanghai.aliyuncs.com/tjrf/lego:{{ tag }} # alicloud arc 构建好的镜像
    container_name: lego-backend
    ports:
      - 7001:7001
    env_file:
      - .env