name: 自动部署到新版本服务器
# 在特定 tag 被 push 以后触发
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      # checkout 代码
      - uses: actions/checkout@v2
      # 创建env文件
      # build docker image
      # start the app
      - name: 'create env file'
        run: |
          touch .env
          echo PING_ENV=${{ secrets.PING_ENV }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo GITEE_CID=${{ secrets.GITEE_CID }} >> .env
          echo GITEE_SECRET=${{ secrets.GITEE_SECRET }} >> .env
          echo ALC_ACCESS_KEY=${{ secrets.ALC_ACCESS_KEY }} >> .env
          echo ALC_ACCESS_SECTET=${{ secrets.ALC_ACCESS_SECTET }} >> .env
          echo MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }} >> .env
          echo MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }} >> .env
          echo MONGO_DB_USERNAME=${{ secrets.MONGO_DB_USERNAME }} >> .env
          echo MONGO_DB_PASSWORD=${{ secrets.MONGO_DB_PASSWORD }} >> .env
          echo REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} >> .env
      # 使用阿里云ACR 完成 docker login
      - name: Login to Aliyun Container Registry（ACR）
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-shanghai.aliyuncs.com
          region-id: cn-shanghai
          username: '${{ secrets.ACR_USERNAME }}'
          password: '${{ secrets.ACR_PASSWORD }}'
      # 使用正确的github tag 对应 ACR tag 进行 docker build
      - name: Build image from ACR docker
        run: docker build --tag 'registry.cn-shanghai.aliyuncs.com/tjrf/lego:${{ github.ref_name }}' .
      # 使用标记的 tag 进行 push
      - name: Push Image to ACR
        run: docker push registry.cn-shanghai.aliyuncs.com/tjrf/lego:${{ github.ref_name }}
      # 查找 docker-compose-online 文件 并且完成版本替换
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "{{ tag }}"
          replace: ${{ github.ref_name }}
          include: "docker-compose-online.yml"
      # 拷贝必须文件到一个文件夹，包括 .env docker-compose-online.yml mongo-entrypoint
      - name: Copy necessary files into one foler
        run: |
          mkdir lego-backend
          cp .env docker-compose-online.yml lego-backend
          cp -r mongo-entrypoint lego-backend
      # 通过scp 拷贝必须文件夹到服务器
      - name: Copy lego-backend folder via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: 'lego-backend'
          target: '~'
      # 通过SSH 登录然后重启服务
      - name: Executing ssh and restart docker
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script_stop: true
          # * 登录阿里云 ACR
          # 停止服务 docker-compose down
          # 启动服务 docker-compose up -d
          # 清理工作
          script: |
            docker login --username=${{ secrets.ACR_USERNAME }} --password=${{ secrets.ACR_PASSWORD }} registry.cn-shanghai.aliyuncs.com
            cd ~/lego-backend/
            docker-compose -f docker-compose-online.yml down
            docker-compose -f docker-compose-online.yml up -d
            rm -rf .env
            docker logout registry.cn-shanghai.aliyuncs.com